[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#fdf6e3"
foreground = "#586e75"

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.offset]
y = -2

[terminal.shell]
program = "bash"

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 0

[terminal]
