[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.offset]
y = -2

[terminal.shell]
program = "bash"

[window]
decorations = "none"
startup_mode = "Maximized"
