[user]
name = "Erik Fasterius"
email = "erik.fasterius@outlook.com"

[ui]
default-command = ["log", "-T", "my_log_comfortable"]

[git]
subprocess = true

[colors]
"bookmarks" = "yellow"
"change_id" = "blue"
"commit_id" = "cyan"
"diff token" = {underline = false}
"author" = "cyan"
"email" = "cyan"
"description" = {bold = true}
"description placeholder" = {fg = "bright red", bold = false, italic = true}
"empty description placeholder" = {fg = "bright red", bold = false, italic = true}
"empty" = {fg = "bright red", bold = false, italic = true}
"git_head" = "yellow"
"git_refsl" = "yellow"
"node working_copy" = { fg = "yellow", bold = true }
"rest" = "bright cyan"
"root" = "yellow"
"timestamp" = "blue"
"working_copy author" = "cyan"
"working_copy bookmarks" = "yellow"
"working_copy change_id" = "blue"
"working_copy commit_id" = "cyan"
"working_copy description placeholder" = {fg = "yellow", bold = true, italic = true}
"working_copy empty description placeholder" = {fg = "yellow", bold = true, italic = true}
"working_copy empty" = {fg = "yellow", bold = true, italic = true}
"working_copy timestamp" = "blue"
