default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/commit-check/commit-check
    rev: v2.5.0
    hooks:
      - id: check-message
        stages: [commit-msg]
      - id: check-branch
        stages: [pre-commit]
